global:
  scrape_interval:     5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: mesherserver
    metrics_path: '/v1/mesher/metrics'
    static_configs:
      - targets: ['49.4.13.154:30102']
  - job_name: mesherclient
    metrics_path: '/v1/mesher/metrics'
    static_configs:
      - targets: ['49.4.15.78:30102']


